CLASS zbp_r_aonlineshop_002 DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
  FOR BEHAVIOR OF zr_aonlineshop_002 .

  PUBLIC SECTION.
    CLASS-DATA mapped_purchase_requisition TYPE RESPONSE FOR MAPPED i_purchaserequisitiontp.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZBP_R_AONLINESHOP_002 IMPLEMENTATION.
ENDCLASS.
